apiVersion: v1
kind: Service
metadata:
  name: patio-api
  labels:
    app: patio
    tier: api
spec:
  ports:
    - port: {{ .Values.api.service.port }}
      protocol: TCP
      targetPort: {{ .Values.api.service.port }}
  selector:
    app: patio
    tier: api
  clusterIP: None