apiVersion: apps/v1
kind: Deployment
metadata:
  name: patio-api
  labels:
    app: patio
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patio
      tier: api
  template:
    metadata:
      name: patio-api
      labels:
        app: patio
        tier: api
    spec:
      containers:
        - name: patio-api        
          image: kaleidosteam/patio-api:{{ .Values.api.deployment.version }}          
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: patio-config          
          resources:
            requests:
              memory: {{ .Values.api.deployment.resources.memory }}
              cpu: {{ .Values.api.deployment.resources.cpu }}
            limits:
              memory: {{ .Values.api.deployment.resources.memory }}
              cpu: {{ .Values.api.deployment.resources.cpu }}              
            