apiVersion: v1
kind: ConfigMap
metadata:
  name: patio-config
  labels:
    app: patio
data:
    MICRONAUT_ENVIRONMENTS: prod
    PATIO_LOCALE: {{ .Values.api.deployment.locale }}
    PATIO_JDBC_URL: {{ .Values.api.deployment.database.url }}
    PATIO_JDBC_USER: {{ .Values.api.deployment.database.username }}
    PATIO_JDBC_PASSWORD: {{ .Values.api.deployment.database.password }}
    PATIO_JDBC_DRIVER: {{ .Values.api.deployment.database.driver }}
    PATIO_AWS_EMAIL_ENABLED: "{{ .Values.api.deployment.email.enabled }}"
    PATIO_AWS_EMAIL_SOURCE: {{ .Values.api.deployment.email.source }}
    PATIO_AWS_ACCESS_KEY: {{ .Values.api.deployment.security.aws.access_key }}
    PATIO_AWS_SECRET_KEY: {{ .Values.api.deployment.security.aws.secret_key }}
    PATIO_AWS_EMAIL_REGION: {{ .Values.api.deployment.security.aws.email_region }}
    PATIO_OAUTH2_KEY: {{ .Values.api.deployment.security.oauth2.key }}
    PATIO_OAUTH2_SECRET: {{ .Values.api.deployment.security.oauth2.secret }}
    PATIO_OAUTH2_CALLBACK: {{ .Values.api.deployment.security.oauth2.callback }}
    PATIO_JWT_SECRET: {{ .Values.api.deployment.security.jwt.secret }}
    PATIO_JWT_DAYS: "{{ .Values.api.deployment.security.jwt.days }}"
    PATIO_JWT_ALGO: {{ .Values.api.deployment.security.jwt.algorithm }}
    PATIO_JWT_ISSUER: {{ .Values.api.deployment.security.jwt.issuer }}
    PATIO_DUSER_ENABLED: "{{ .Values.api.deployment.security.duser.enabled }}"
    PATIO_DUSER_NAME: {{ .Values.api.deployment.security.duser.name }}
    PATIO_DUSER_EMAIL: {{ .Values.api.deployment.security.duser.email }}
    PATIO_DUSER_PASSWORD: {{ .Values.api.deployment.security.duser.password }}
    PATIO_HOST: {{ .Values.api.deployment.host }}