apiVersion: apps/v1
kind: Deployment
metadata:
  name: patio-db
  labels:
    app: patio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patio
      tier: postgres
  template:
    metadata:
      name: patio-db
      labels:
        app: patio
        tier: postgres
    spec:
      containers:
        - image: postgres:10-alpine
          name: postgres
          envFrom:
            - configMapRef:
                name: patio-db-config            
          ports:
            - containerPort: {{ .Values.db.deployment.port }}
              name: patio-db
          volumeMounts:
            - mountPath: {{ .Values.db.deployment.disk_mount }}
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: patio-db-pv-claim