apiVersion: apps/v1
kind: Deployment
metadata:
  name: patio-db
  labels:
    app: patio
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patio
      tier: db
  template:
    metadata:
      name: patio-db
      labels:
        app: patio
        tier: db
    spec:
      containers:
        - name: patio-db
          image: postgres:10-alpine
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: patio-db-config            
          ports:
            - containerPort: {{ .Values.db.deployment.port }}
              name: patio-db