apiVersion: apps/v1
kind: Deployment
metadata:
  name: patio-db
  labels:
    app: patio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patio
      tier: postgres
  template:
    metadata:
      name: patio-db
      labels:
        app: patio
        tier: postgres
    spec:
      containers:
        - image: postgres:10-alpine
          name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.deployment.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.deployment.password }}
            - name: POSTGRES_DB
              value: {{ .Values.db.deployment.name }}
          ports:
            - containerPort: {{ .Values.db.deployment.port }}
              name: patio-db