apiVersion: v1
kind: Service
metadata:
  name: patio-db
  labels:
    app: patio

spec:
  ports:
    - port: {{ .Values.db.service.port }}
  selector:
    app: patio
    tier: postgres
  clusterIP: None