apiVersion: apps/v1
kind: Deployment
metadata:
  name: patio-front
  labels:
    app: patio
    tier: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patio
      tier: front
  template:
    metadata:
      name: patio-front
      labels:
        app: patio
        tier: front
    spec:
      containers:
        - name: patio-front
          image: kaleidosteam/patio-front:{{ .Values.front.deployment.version }}
          imagePullPolicy: Always
