apiVersion: v1
kind: Service
metadata:
  name: patio-front
  labels:
    app: patio
    tier: front
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.front.service.port }}
  selector:
    app: patio
    tier: front